# Generated by Django 5.1.15 on 2026-05-07 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tspan_start", models.FloatField(default=0.0)),
                ("tspan_end", models.FloatField(default=48.0)),
                ("period", models.FloatField(default=24.0)),
                ("psi", models.FloatField(default=100.0)),
                ("L", models.FloatField(default=30.0)),
                ("saveat", models.FloatField(default=0.1)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Patch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("initial_pop", models.FloatField(default=0.0)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patches",
                        to="modeler.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        help_text="Snapshot of the project config at run time"
                    ),
                ),
                ("result_path", models.CharField(blank=True, max_length=512)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="modeler.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vff",
                    models.FloatField(
                        default=120.0, help_text="Free-flow velocity (km/h)"
                    ),
                ),
                (
                    "nc_half_ff",
                    models.FloatField(
                        default=0.3,
                        help_text="Inverse capacity (corridor sat. fraction at half free-flow)",
                    ),
                ),
                (
                    "vsharp",
                    models.FloatField(
                        default=1.0, help_text="Sharpness of velocity-vs-density curve"
                    ),
                ),
                (
                    "demhf",
                    models.FloatField(
                        default=1000.0,
                        help_text="Demand half-flux (saturation point in vehicles)",
                    ),
                ),
                (
                    "shift",
                    models.FloatField(
                        default=0.0, help_text="Phase shift of demand peak (hours)"
                    ),
                ),
                (
                    "dur",
                    models.FloatField(default=0.97, help_text="Diurnal demand width"),
                ),
                (
                    "dsharp",
                    models.FloatField(
                        default=100.0, help_text="Sharpness of diurnal demand peak"
                    ),
                ),
                (
                    "bgd",
                    models.FloatField(default=0.0, help_text="Background demand floor"),
                ),
                ("onff", models.FloatField(default=5000.0, help_text="On-ramp scale")),
                (
                    "on_half",
                    models.FloatField(default=0.5, help_text="On-ramp half-saturation"),
                ),
                (
                    "onsharp",
                    models.FloatField(default=1.0, help_text="On-ramp sharpness"),
                ),
                (
                    "from_patch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="modeler.patch",
                    ),
                ),
                (
                    "to_patch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="modeler.patch",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="modeler.project",
                    ),
                ),
            ],
            options={
                "ordering": ["from_patch__display_order", "to_patch__display_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "from_patch", "to_patch"),
                        name="unique_edge_per_pair",
                    )
                ],
            },
        ),
    ]
