# Generated by Django 5.1.15 on 2026-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_template",
            field=models.BooleanField(
                default=False,
                help_text="Read-only baseline; users clone from it to start a new sandbox.",
            ),
        ),
    ]
